package com.lfc.mysql.greenDao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lfc.mysql.DataBeans.UserD;
import com.lfc.mysql.DataBeans.Student;

import com.lfc.mysql.greenDao.UserDDao;
import com.lfc.mysql.greenDao.StudentDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDDaoConfig;
    private final DaoConfig studentDaoConfig;

    private final UserDDao userDDao;
    private final StudentDao studentDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDDaoConfig = daoConfigMap.get(UserDDao.class).clone();
        userDDaoConfig.initIdentityScope(type);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        userDDao = new UserDDao(userDDaoConfig, this);
        studentDao = new StudentDao(studentDaoConfig, this);

        registerDao(UserD.class, userDDao);
        registerDao(Student.class, studentDao);
    }
    
    public void clear() {
        userDDaoConfig.clearIdentityScope();
        studentDaoConfig.clearIdentityScope();
    }

    public UserDDao getUserDDao() {
        return userDDao;
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

}
