package com.lfc.mysql.greenDao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.lfc.mysql.DataBeans.OrdersD;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ORDERS_D".
*/
public class OrdersDDao extends AbstractDao<OrdersD, Long> {

    public static final String TABLENAME = "ORDERS_D";

    /**
     * Properties of entity OrdersD.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CustomerID = new Property(1, Long.class, "customerID", false, "CUSTOMER_ID");
        public final static Property StrTime = new Property(2, String.class, "strTime", false, "STR_TIME");
        public final static Property StrNote = new Property(3, String.class, "strNote", false, "STR_NOTE");
    }


    public OrdersDDao(DaoConfig config) {
        super(config);
    }
    
    public OrdersDDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ORDERS_D\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CUSTOMER_ID\" INTEGER," + // 1: customerID
                "\"STR_TIME\" TEXT," + // 2: strTime
                "\"STR_NOTE\" TEXT);"); // 3: strNote
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ORDERS_D\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, OrdersD entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long customerID = entity.getCustomerID();
        if (customerID != null) {
            stmt.bindLong(2, customerID);
        }
 
        String strTime = entity.getStrTime();
        if (strTime != null) {
            stmt.bindString(3, strTime);
        }
 
        String strNote = entity.getStrNote();
        if (strNote != null) {
            stmt.bindString(4, strNote);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, OrdersD entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long customerID = entity.getCustomerID();
        if (customerID != null) {
            stmt.bindLong(2, customerID);
        }
 
        String strTime = entity.getStrTime();
        if (strTime != null) {
            stmt.bindString(3, strTime);
        }
 
        String strNote = entity.getStrNote();
        if (strNote != null) {
            stmt.bindString(4, strNote);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public OrdersD readEntity(Cursor cursor, int offset) {
        OrdersD entity = new OrdersD( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // customerID
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // strTime
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // strNote
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, OrdersD entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCustomerID(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setStrTime(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setStrNote(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(OrdersD entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(OrdersD entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(OrdersD entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
