package com.lfc.mysql.greenDao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.lfc.mysql.DataBeans.Student;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "STUDENT".
*/
public class StudentDao extends AbstractDao<Student, Long> {

    public static final String TABLENAME = "STUDENT";

    /**
     * Properties of entity Student.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property StrUId = new Property(0, Long.class, "strUId", true, "_id");
        public final static Property StuNo = new Property(1, String.class, "stuNo", false, "STU_NO");
        public final static Property StuName = new Property(2, String.class, "stuName", false, "STU_NAME");
        public final static Property StuSex = new Property(3, String.class, "stuSex", false, "STU_SEX");
        public final static Property StuScore = new Property(4, int.class, "stuScore", false, "STU_SCORE");
        public final static Property Stuads = new Property(5, String.class, "stuads", false, "STUADS");
    }


    public StudentDao(DaoConfig config) {
        super(config);
    }
    
    public StudentDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"STUDENT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: strUId
                "\"STU_NO\" TEXT," + // 1: stuNo
                "\"STU_NAME\" TEXT," + // 2: stuName
                "\"STU_SEX\" TEXT," + // 3: stuSex
                "\"STU_SCORE\" INTEGER NOT NULL ," + // 4: stuScore
                "\"STUADS\" TEXT);"); // 5: stuads
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_STUDENT_STU_NO ON \"STUDENT\"" +
                " (\"STU_NO\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"STUDENT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Student entity) {
        stmt.clearBindings();
 
        Long strUId = entity.getStrUId();
        if (strUId != null) {
            stmt.bindLong(1, strUId);
        }
 
        String stuNo = entity.getStuNo();
        if (stuNo != null) {
            stmt.bindString(2, stuNo);
        }
 
        String stuName = entity.getStuName();
        if (stuName != null) {
            stmt.bindString(3, stuName);
        }
 
        String stuSex = entity.getStuSex();
        if (stuSex != null) {
            stmt.bindString(4, stuSex);
        }
        stmt.bindLong(5, entity.getStuScore());
 
        String stuads = entity.getStuads();
        if (stuads != null) {
            stmt.bindString(6, stuads);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Student entity) {
        stmt.clearBindings();
 
        Long strUId = entity.getStrUId();
        if (strUId != null) {
            stmt.bindLong(1, strUId);
        }
 
        String stuNo = entity.getStuNo();
        if (stuNo != null) {
            stmt.bindString(2, stuNo);
        }
 
        String stuName = entity.getStuName();
        if (stuName != null) {
            stmt.bindString(3, stuName);
        }
 
        String stuSex = entity.getStuSex();
        if (stuSex != null) {
            stmt.bindString(4, stuSex);
        }
        stmt.bindLong(5, entity.getStuScore());
 
        String stuads = entity.getStuads();
        if (stuads != null) {
            stmt.bindString(6, stuads);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Student readEntity(Cursor cursor, int offset) {
        Student entity = new Student( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // strUId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // stuNo
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // stuName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // stuSex
            cursor.getInt(offset + 4), // stuScore
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // stuads
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Student entity, int offset) {
        entity.setStrUId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setStuNo(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setStuName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setStuSex(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setStuScore(cursor.getInt(offset + 4));
        entity.setStuads(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Student entity, long rowId) {
        entity.setStrUId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Student entity) {
        if(entity != null) {
            return entity.getStrUId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Student entity) {
        return entity.getStrUId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
